name: WorldEditya2
main: Deceitya\WorldEditya2\Main
version: 1.0.0
api: 3.11.7
load: POSTWORLD
author: deceitya
description: わ～るどえでぃちゃ
website: https://github.com/deceitya/WorldEditya2

permissions:
  worldeditya2.command.pos1:
    description: Allows the admin to run the pos1 command
    default: op
  worldeditya2.command.pos2:
    description: Allows the admin to run the pos2 command
    default: op
  worldeditya2.command.set:
    description: Allows the admin to run the set command
    default: op
  worldeditya2.command.undo:
    description: Allows the admin to run the undo command
    default: op
  worldeditya2.command.replace:
    description: Allows the admin to run the replace command
    default: op